import { poppins } from "@/utils/Fonts";
import "./globals.css";
import { GlobalProvider } from "@/Provider/GlobalProvider";
import Navbar from "@/pages/shere/Navbar";
import Footer from "@/pages/shere/Footer";

export const metadata = {
  title: "Jm Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <GlobalProvider>
          <header>
            <Navbar></Navbar>
          </header>
          <main className="min-h-[calc(100vh-200px)]">{children}</main>
          <footer>
            <Footer></Footer>
          </footer>
        </GlobalProvider>
      </body>
    </html>
  );
}
